# Jekyll configuration for Learn Programming with Smalltalk

# Site settings
title: "Learn Programming with Smalltalk"
description: "A comprehensive, beginner-friendly introduction to programming using modern open-source Smalltalk environments"
author: "Learn Smalltalk Project"
baseurl: "/Learn-Programming-with-Smalltalk"
url: "https://cloudstreet-dev.github.io"

# Theme
theme: jekyll-theme-cayman
# Alternative themes you can try:
# theme: jekyll-theme-minimal
# theme: jekyll-theme-architect
# theme: jekyll-theme-slate

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: smalltalk

# Plugins (automatically included with github-pages gem)
plugins:
  - jekyll-seo-tag
  - jekyll

# Navigation structure
navigation:
  - title: Home
    url: /
  - title: Table of Contents
    url: /TABLE_OF_CONTENTS
  - title: Start Reading
    url: /chapters/chapter-01-what-is-programming
  - title: Technical Review
    url: /TECHNICAL_REVIEW

# Exclude from processing
exclude:
  - .gitignore
  - link_check_report.md
  - README_DEV.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include in processing
include:
  - _config.yml

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# GitHub Pages specific
github:
  repository_url: "https://github.com/cloudstreet-dev/Learn-Programming-with-Smalltalk"

# Social links
social:
  github: cloudstreet-dev/Learn-Programming-with-Smalltalk

# Analytics (add your tracking ID if desired)
# google_analytics: UA-XXXXXXXXX-X

# SEO settings
logo: /assets/images/logo.png
social:
  name: Learn Programming with Smalltalk
  links:
    - https://github.com/cloudstreet-dev/Learn-Programming-with-Smalltalk

# Color scheme (for Cayman theme)
color_scheme: default
